export interface Login {
    UserId: string;
    UserName: string;
    Password: string;
    Address: string;
    City: string;
    ZIP: string;
    State: string;
    EMail: string;
    Phone1: string;
    Phone2: string;
    CellPhone: string;
    CreatedAt?: any;
    CreatedBy?: any;
    ModifyAt: string;
    ModifyBy: string;
    UserType: string;
    RollId: string;
    IsSuperUser: string;
    IsDeleted: string;
    ReportTo: string;
    DptId: string;
    DesgId: string;
    ContactId: string;
    SubUser: string;
    MailPassword: string;
    MailLogin: string;
    imei: string;
}